---

- name: create mysql_exporter configuration directories
  ansible.builtin.file:
    path: "{{ mysql_exporter_config_dir }}"
    state: directory
    owner: root
    group: "{{ mysql_exporter_system_group }}"
    mode: 0775

- name: create mysql_exporter configuration
  ansible.builtin.template:
    src: "default/mysql-exporter.j2"
    dest: "{{ mysql_exporter_config_dir }}/mysql-exporter"
    force: true
    owner: root
    group: "{{ mysql_exporter_system_group }}"
    mode: 0640
  # notify:
  #   - restart mysql_exporter

...
