---

- name: restart mysql_exporter
  become: true
  ansible.builtin.service:
    name: mysql-exporter
    state: restarted

- name: reload mysql-exporter
  become: true
  ansible.builtin.service:
    name: mysql-exporter
    state: reloaded

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
